# Generated by Django 3.1.5 on 2021-02-08 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_owed', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
