# Generated by Django 3.1.5 on 2021-02-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
